<?php
declare(strict_types=1);
session_start();
if(isset($_GET['logout'])){session_destroy();header('Location:login.php');exit;}
if(empty($_SESSION['acai_admin'])){header('Location:login.php');exit;}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel | Açaí do Bom</title><link rel="stylesheet" href="admin.css"></head><body>
<div class="admin-layout">
<aside><a class="admin-logo" href="../../"><span>A</span><div><b>Açaí do Bom</b><small>GESTÃO DO CARDÁPIO</small></div></a><nav><button class="active" data-tab="dashboard">▦ Visão geral</button><button data-tab="orders">▣ Pedidos <b id="pending-badge">0</b></button><button data-tab="products">⬡ Produtos</button><button data-tab="appearance">◈ Aparência</button><button data-tab="settings">⚙ Configurações</button></nav><a class="logout" href="?logout=1">↪ Sair do painel</a></aside>
<main>
<header class="admin-head"><div><a href="../../">← Ver cardápio</a><h1>Painel de controle</h1><p>Gerencie toda a operação do Açaí do Bom.</p></div><button id="save-all">✓ Publicar alterações</button></header>
<div class="notice" id="notice" hidden></div>
<section class="tab active" data-panel="dashboard"><div class="title"><small>RESUMO DE HOJE</small><h2>Visão geral</h2></div><div class="stats"><article><i>▣</i><span><small>Pedidos hoje</small><b id="stat-orders">0</b></span></article><article><i>↗</i><span><small>Faturamento hoje</small><b id="stat-revenue">R$ 0,00</b></span></article><article><i>◷</i><span><small>Em andamento</small><b id="stat-pending">0</b></span></article><article><i>⬡</i><span><small>Produtos ativos</small><b id="stat-products">0</b></span></article></div><div class="dashboard-grid"><article class="card"><h3>Pedidos recentes</h3><div id="recent-orders"></div></article><article class="card operation"><h3>Operação</h3><div id="operation-summary"></div></article></div></section>
<section class="tab" data-panel="orders"><div class="title"><small>CONTROLE DA COZINHA</small><h2>Pedidos</h2></div><div class="orders" id="orders-list"></div></section>
<section class="tab" data-panel="products"><div class="title row"><div><small>CATÁLOGO</small><h2>Produtos</h2><p id="product-count"></p></div><button class="primary" id="new-product">+ Novo produto</button></div><div class="product-list" id="admin-products"></div></section>
<section class="tab" data-panel="appearance"><div class="title"><small>IDENTIDADE DA MARCA</small><h2>Aparência</h2><p>Altere logo banner e cores sem mexer no código.</p></div><div class="settings-grid"><article class="card"><h3>Logo da loja</h3><div class="upload-preview logo" id="logo-preview">A</div><label class="upload">Enviar nova logo<input type="file" data-upload="logo" accept="image/*"></label><label>URL da logo<input id="logo-url"></label></article><article class="card"><h3>Banner principal</h3><div class="upload-preview banner" id="banner-preview"></div><label class="upload">Trocar banner<input type="file" data-upload="banner" accept="image/*"></label><label>URL do banner<input id="banner-url"></label></article><article class="card"><h3>Cores da marca</h3><label>Cor principal<div class="color"><input type="color" id="primary-color"><input id="primary-text"></div></label><label>Cor de destaque<div class="color"><input type="color" id="accent-color"><input id="accent-text"></div></label></article><article class="card"><h3>Texto principal</h3><label>Nome da loja<input id="store-name"></label><label>Chamada do banner<input id="store-tagline"></label></article></div></section>
<section class="tab" data-panel="settings"><div class="title"><small>OPERAÇÃO E INTEGRAÇÕES</small><h2>Configurações</h2></div><div class="settings-grid"><article class="card"><h3>Loja e entrega</h3><label class="switch-line"><span><b>Loja aberta</b><small>Indica que está recebendo pedidos</small></span><input type="checkbox" id="store-open"></label><label>Cidade atendida<input id="store-city"></label><label>Endereço<input id="store-address"></label><div class="two"><label>Taxa de entrega<input type="number" step=".01" id="delivery-fee"></label><label>Pedido mínimo<input type="number" step=".01" id="min-order"></label></div><label>Tempo estimado<input id="estimated-time"></label></article><article class="card"><h3>Pedidos e pagamentos</h3><label>WhatsApp dos pedidos<input id="store-whatsapp"></label><label>E-mail dos pedidos<input id="order-email"></label><label>Chave PIX<input id="pix-key"></label><label>Link do gateway de pagamento<input id="payment-link"></label></article><article class="card"><h3>Rastreamento</h3><p>Use apenas os identificadores das plataformas.</p><label>Meta Pixel ID<input id="meta-pixel"></label><label>Google Tag Manager<input id="gtm-id" placeholder="GTM-XXXXXXX"></label><label>Google Analytics 4<input id="ga4-id" placeholder="G-XXXXXXXXXX"></label></article><article class="card"><header class="card-row"><h3>Categorias</h3><button id="add-category">+ Adicionar</button></header><div id="category-editor"></div></article></div></section>
</main></div>
<div class="dialog" id="product-dialog" hidden><form id="product-form"><button type="button" class="close" data-close-product>×</button><h2 id="editor-title">Novo produto</h2><div class="editor-scroll"><div class="product-basic"><div><div class="product-photo" id="product-photo">⬡</div><label class="upload">Enviar imagem<input type="file" data-upload="product" accept="image/*"></label></div><div><label>Nome do produto<input id="edit-name" required></label><label>Categoria<select id="edit-category"></select></label><div class="two"><label>Preço<input id="edit-price" type="number" step=".01" required></label><label>Selo<input id="edit-badge" placeholder="Mais pedido"></label></div></div></div><label>Descrição<textarea id="edit-description"></textarea></label><label>URL da imagem<input id="edit-image"></label><div class="two switches"><label><input id="edit-active" type="checkbox"> Produto ativo</label><label><input id="edit-featured" type="checkbox"> Destaque</label></div><section class="addons-editor"><header><div><h3>Adicionais e etapas</h3><p>Grupos obrigatórios ou opcionais para montar o pedido.</p></div><button type="button" id="add-group">+ Novo grupo</button></header><div id="addon-groups"></div></section></div><footer><button type="button" data-close-product>Cancelar</button><button class="primary">Salvar produto</button></footer></form></div>
<div class="confirm" id="confirm-delete" hidden><div><h3>Excluir produto?</h3><p>Ele será removido após publicar as alterações.</p><footer><button id="cancel-delete">Cancelar</button><button id="do-delete">Excluir</button></footer></div></div>
<script src="admin.js"></script></body></html>